
#server:
 # port: 80

  #项目配置访问路径
  #servlet:
    #context-path: /website

#我们能配置的属性都是来源于这个功能的properties类
spring:
  http:
    encoding:
      enabled: true
      charset: utf-8
      force: true
  datasource:
    druid:
      username: mrspeak
      password: Mrspeak@2019
      url: jdbc:mysql://49.234.110.149:3306/mrspeak
      driver-class-name: com.mysql.jdbc.Driver
      filters: stat,wall,log4j
      initial-size: 5
      max-active: 20
      max-wait: 2000
      min-idle: 2
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 30000
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
      validation-query: SELECT 1 FROM DUAL

  #    filters: stat,wall,log4j
#    maxActive: 100
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 1 FROM DUAL
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 50
#    maxPoolPreparedStatementPerConnectionSize: 20
#    useGlobalDataSourceStat: true
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  activemq:
    broker-url:
#开发springboot的debug模式
#debug: true




mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
